/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mujigue.view;

import java.util.List;
import mujigue.app.App;
import mujigue.config.PelangganTableModel;
import mujigue.controller.DaftarMejaController;
import mujigue.controller.MejaFormController;
import mujigue.model.Pelanggan;

/**
 *
 * @author herma
 */
public class DaftarMejaForm extends javax.swing.JInternalFrame {

    private final DaftarMejaController dmc = new DaftarMejaController(this);
    /**
     * @return the btnCloseDaftarMeja
     */
    public javax.swing.JButton getBtnCloseDaftarMeja() {
        return btnCloseDaftarMeja;
    }

    /**
     * @param btnCloseDaftarMeja the btnCloseDaftarMeja to set
     */
    public void setBtnCloseDaftarMeja(javax.swing.JButton btnCloseDaftarMeja) {
        this.btnCloseDaftarMeja = btnCloseDaftarMeja;
    }

    /**
     * @return the btnHapusMeja
     */
    public javax.swing.JButton getBtnHapusMeja() {
        return btnHapusMeja;
    }

    /**
     * @param btnHapusMeja the btnHapusMeja to set
     */
    public void setBtnHapusMeja(javax.swing.JButton btnHapusMeja) {
        this.btnHapusMeja = btnHapusMeja;
    }

    /**
     * @return the btnRefreshDM
     */
    public javax.swing.JButton getBtnRefreshDM() {
        return btnRefreshDM;
    }

    /**
     * @param btnRefreshDM the btnRefreshDM to set
     */
    public void setBtnRefreshDM(javax.swing.JButton btnRefreshDM) {
        this.btnRefreshDM = btnRefreshDM;
    }

    /**
     * @return the btnTambahMeja
     */
    public javax.swing.JButton getBtnTambahMeja() {
        return btnTambahMeja;
    }

    /**
     * @param btnTambahMeja the btnTambahMeja to set
     */
    public void setBtnTambahMeja(javax.swing.JButton btnTambahMeja) {
        this.btnTambahMeja = btnTambahMeja;
    }

    /**
     * @return the btnUbahStatusTerisi
     */
    public javax.swing.JButton getBtnUbahStatusTerisi() {
        return btnUbahStatusTerisi;
    }

    /**
     * @param btnUbahStatusTerisi the btnUbahStatusTerisi to set
     */
    public void setBtnUbahStatusTerisi(javax.swing.JButton btnUbahStatusTerisi) {
        this.btnUbahStatusTerisi = btnUbahStatusTerisi;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the tblDaftarMeja
     */
    public javax.swing.JTable getTblDaftarMeja() {
        return tblDaftarMeja;
    }

    /**
     * @param tblDaftarMeja the tblDaftarMeja to set
     */
    public void setTblDaftarMeja(javax.swing.JTable tblDaftarMeja) {
        this.tblDaftarMeja = tblDaftarMeja;
    }

    /**
     * Creates new form DaftarMejaIntForm
     */
    public DaftarMejaForm() {
        initComponents();
        dmc.showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambahMeja = new javax.swing.JButton();
        btnUbahStatusTerisi = new javax.swing.JButton();
        btnHapusMeja = new javax.swing.JButton();
        btnCloseDaftarMeja = new javax.swing.JButton();
        btnRefreshDM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDaftarMeja = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        btnTambahMeja.setText("Tambah Meja");
        btnTambahMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMejaActionPerformed(evt);
            }
        });

        btnUbahStatusTerisi.setText("Ubah Status Terisi");
        btnUbahStatusTerisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahStatusTerisiActionPerformed(evt);
            }
        });

        btnHapusMeja.setText("Hapus Meja");
        btnHapusMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMejaActionPerformed(evt);
            }
        });

        btnCloseDaftarMeja.setText("Close");
        btnCloseDaftarMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseDaftarMejaActionPerformed(evt);
            }
        });

        btnRefreshDM.setText("Refresh Data");
        btnRefreshDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshDMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUbahStatusTerisi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRefreshDM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCloseDaftarMeja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUbahStatusTerisi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambahMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapusMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshDM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCloseDaftarMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDaftarMeja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDaftarMeja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDaftarMejaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDaftarMeja);

        jLabel2.setText("MUJIGUE RESTAURANT");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("DAFTAR MEJA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMejaActionPerformed
        // TODO add your handling code here:
        MejaForm form = new MejaForm();
        form.setVisible(true);
        form.setFocusable(true);
        getDesktopPane().add(form);
    }//GEN-LAST:event_btnTambahMejaActionPerformed

    private void btnUbahStatusTerisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahStatusTerisiActionPerformed
        // TODO add your handling code here:
        dmc.editStatusMeja();
    }//GEN-LAST:event_btnUbahStatusTerisiActionPerformed

    private void btnHapusMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMejaActionPerformed
        // TODO add your handling code here:
        dmc.deleteMeja();
    }//GEN-LAST:event_btnHapusMejaActionPerformed

    private void btnRefreshDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDMActionPerformed
        // TODO add your handling code here:
        dmc.showData();
    }//GEN-LAST:event_btnRefreshDMActionPerformed

    private void tblDaftarMejaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDaftarMejaMouseClicked
        // TODO add your handling code here:
        dmc.getMeja();
    }//GEN-LAST:event_tblDaftarMejaMouseClicked

    private void btnCloseDaftarMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseDaftarMejaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseDaftarMejaActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        dmc.clear();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseDaftarMeja;
    private javax.swing.JButton btnHapusMeja;
    private javax.swing.JButton btnRefreshDM;
    private javax.swing.JButton btnTambahMeja;
    private javax.swing.JButton btnUbahStatusTerisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDaftarMeja;
    // End of variables declaration//GEN-END:variables
}
