/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mujigue.view;

import mujigue.controller.MejaFormController;

/**
 *
 * @author herma
 */
public class MejaForm extends javax.swing.JInternalFrame {
    private final MejaFormController mfc = new MejaFormController(this);

    /**
     * @return the edtKapasitasMeja
     */
    public javax.swing.JTextField getEdtKapasitasMeja() {
        return edtKapasitasMeja;
    }

    /**
     * @param edtKapasitasMeja the edtKapasitasMeja to set
     */
    public void setEdtKapasitasMeja(javax.swing.JTextField edtKapasitasMeja) {
        this.edtKapasitasMeja = edtKapasitasMeja;
    }

    /**
     * @return the edtLokasiMeja
     */
    public javax.swing.JTextField getEdtLokasiMeja() {
        return edtLokasiMeja;
    }

    /**
     * @param edtLokasiMeja the edtLokasiMeja to set
     */
    public void setEdtLokasiMeja(javax.swing.JTextField edtLokasiMeja) {
        this.edtLokasiMeja = edtLokasiMeja;
    }

    /**
     * @return the edtNoMeja
     */
    public javax.swing.JTextField getEdtNoMeja() {
        return edtNoMeja;
    }

    /**
     * @param edtNoMeja the edtNoMeja to set
     */
    public void setEdtNoMeja(javax.swing.JTextField edtNoMeja) {
        this.edtNoMeja = edtNoMeja;
    }

    /**
     * @return the jButton1
     */
    public javax.swing.JButton getjButton1() {
        return jButton1;
    }

    /**
     * @param jButton1 the jButton1 to set
     */
    public void setjButton1(javax.swing.JButton jButton1) {
        this.jButton1 = jButton1;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * Creates new form MejaForm
     */
    public MejaForm() {
        initComponents();
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        moveToFront();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtNoMeja = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edtKapasitasMeja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtLokasiMeja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        edtNoMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNoMejaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nomor Meja :");

        edtKapasitasMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtKapasitasMejaActionPerformed(evt);
            }
        });

        jLabel2.setText("Kapasitas Meja :");

        edtLokasiMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLokasiMejaActionPerformed(evt);
            }
        });

        jLabel3.setText("Lokasi Meja :");

        jButton1.setText("Tambah Meja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtNoMeja)
                    .addComponent(edtKapasitasMeja)
                    .addComponent(edtLokasiMeja)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(edtNoMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(edtKapasitasMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(edtLokasiMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtNoMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNoMejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNoMejaActionPerformed

    private void edtKapasitasMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtKapasitasMejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtKapasitasMejaActionPerformed

    private void edtLokasiMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLokasiMejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtLokasiMejaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mfc.saveMeja();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edtKapasitasMeja;
    private javax.swing.JTextField edtLokasiMeja;
    private javax.swing.JTextField edtNoMeja;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
